name: Release Docker Image on Tag

on:
  push:
    tags:
      - '*'  # 匹配任意 tag（如 v1.0.0）

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract repo and tag info
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with tag and latest
        run: |
          docker build -t $IMAGE_NAME:$TAG_NAME -t $IMAGE_NAME:latest .

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:$TAG_NAME
          docker push $IMAGE_NAME:latest
